### ISSUE TITLE
I apologize in advance

### ISSUE THREAD

**Issue by MechanicalMagnificus** [LBNL-ETA/Radiance#29]
For faking an issue to ask one question.

Is there a better place to ask questions?

For context,
I've been researching and successfully using Radiance through Vi-Suite in Blender for a few months now
but,
the official website was last updated in 2017 
before me, the official Radiance google group was last used in 2018 to ask if the software was dead
the most recent blog I found was Dion Moult's from 2018
Ryan Southall on YT has the most recent content from one year ago
I reached out to him, and he gave me a link to the VI-Suite google group, which is fairly active still.

My application for Radiance is unfortunately not architectural, but astronautical.
I want to simulate cameras and sensors based on real world sensors and cameras to validate tracking algorithms
Many years ago, NASA used it to validate lighting conditions for repairing the Hubble telescope
It is also officially listed on the Johnson Space-Center Lighting Lab list of tools
I tried reaching out to their office as well as the NASA HQ Public Library and searched the NTRS website.

I have a lot of confidence in Radiance and so much respect for everyone involved in it, just need to know who to ask for help.

**Comment by taoning** [comment]
It's fantastic to hear your unique application!
We have a [discourse](https://discourse.radiance-online.org/) to discuss all things Radiance.

**Comment by MechanicalMagnificus** [comment]
Holy cow! Thank you so much! I'll check it out right now!
