### ISSUE TITLE
Installation issue on Mac OS

### ISSUE THREAD

**Issue by koepferl** [LBNL-ETA/Radiance#30]
Hi, 

thank you in advance for your help in this matter. I am new to radiance. I installed it on Mac OS Ventura there were no errors. however, I am not sure if the installation worked. I don't find for instance ruv in user/bin/

Thanks for your help.

Christine

**Comment by taoning** [comment]
You should have `rvu` inside your `/usr/local/bin`, which I think is the default path to put the binaries by the installer.
If you do `echo $PATH` in your terminal, you should see all the path that the shell will search for, which should include the one mentioned above.

**Comment by koepferl** [comment]
Thank you for replying, unfortunately rvu is not in /usr/local/bin

**Comment by taoning** [comment]
Sorry, it looks like the default location is `/usr/local/radiance`.  So `rvu` should be in `/usr/local/radiance/bin`
The installer should add `/usr/local/radiance/bin` to your PATH.  If you see it in your `echo $PATH`, you should be able to just call `rvu` from your terminal.  If not you need to manually add the path to your `PATH`

**Comment by koepferl** [comment]
Maybe I just describe what I did. I downloaded Radiance_3bdfad85_OSX.pkg (noting else) and moved it to the Application folder. There I opened it and the installation started. It was done and successful.

**Comment by koepferl** [comment]
Hi yes it is there. Thank you. 

1) I added the path by: 
export PATH=~/usr/local/radiance/bin:$PATH

2) I closed the terminal and opened it again

3) how can I check if it worked

**Comment by taoning** [comment]
Run `rtrace -version` in your terminal to check.  It should print out something like this:
`RADIANCE 6.0a lastmod ...`

Note, `export` command just add the path for a terminal session.  The effect is gone after you close the terminal.
You need to add that command to your shell configuration file,  `~/.zshrc` if you are using `zsh`
Also add this to your `.zshrc`:
`export RAYPATH=.:/usr/local/radiance/lib`

**Comment by koepferl** [comment]
hi are you sure about the syntax? My terminal has zsh, but I only have the .zshrc file.

Thanks a lot

**Comment by taoning** [comment]
Yes, that's all you need.

**Comment by koepferl** [comment]
Sorry to bother you again, it did not work

When I do: 
(base) ... ~ % rtrace -version     
zsh: command not found: rtrace


When I do: 
ls ~/../../usr/local/radiance/    

I get: 

bin/  lib/  man/

echo $PATH 

gives me this output

echo $PATH          
/opt/local/bin:/usr/local/bin:/usr/texbin:/Users/greif/opt/anaconda3/bin:/Users/greif/opt/anaconda3/condabin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/opt/X11/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin

this is what my .zshrc looks like:


# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/Users/greif/opt/anaconda3/bin/conda' 'shell.zsh' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/Users/greif/opt/anaconda3/etc/profile.d/conda.sh" ]; then
        . "/Users/greif/opt/anaconda3/etc/profile.d/conda.sh"
    else
        export PATH="/Users/greif/opt/anaconda3/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<

export PATH="/opt/local/bin:/usr/local/bin:/usr/texbin:$PATH"

export EDITOR="/usr/local/bin/mate -w"

export RAYPATH=.:/usr/local/radiance/lib

**Comment by taoning** [comment]
I don't see `/usr/local/radiance/bin` in your `echo $PATH` output. 
Add this line to your `.zshrc` file
`export PATH=/usr/local/radiance/bin:$PATH`

**Comment by koepferl** [comment]
Thanks now it works.

**Comment by koepferl** [comment]
Do you have a good tutorial to start with building simulations

**Comment by Gregungory** [comment]
Hi Christine,

The best forum for getting started with Radiance is our Discourse server.  You can sign up at:

	https://discourse.radiance-online.org/ <https://discourse.radiance-online.org/>

Here's a tutorial page that may be helpful in getting started:

	https://www.radiance-online.org/learning/tutorials <https://www.radiance-online.org/learning/tutorials>

Best,
-Greg

> From: Christine Koepferl ***@***.***>
> Date: February 16, 2024 at 11:29:58 AM PST
> 
> Do you have a good tutorial to start with building simulations
> 
> —

**Comment by koepferl** [comment]
Thank you!

I am currently working through this tutorial.

https://lbnl-eta.github.io/frads/how-to/guide_rad1/

gen room 12 14 3 
-w 0.4 1 2.5 1.8 
-w 3.3 1 2.5 1.8 
-w 6.2 1 2.5 1.8 
-w 9.1 1 2.5 1.8 
-t 0.1 -n aroom

does not work. It returns me the following error:

gen room 12 14 3 \
-w 0.4 1 2.5 1.8 
-w 3.3 1 2.5 1.8 
-w 6.2 1 2.5 1.8 
-w 9.1 1 2.5 1.8 \
-t 0.1 -n aroom
usage: gen room [-h] [-w start_x start_z width height] [-n NAME] [-t Facade thickness] [-r ROTATE] width depth flrflr flrclg
gen room: error: the following arguments are required: flrclg

Just to be sure, I currently have version:

In [1]: import frads

In [2]: print(frads.version)
0.2.10

However the installation of the below did not quite work, because a file was missing:

pip install git+https://github.com/taoning/pyenergyplus_wheels
Collecting git+https://github.com/taoning/pyenergyplus_wheels
Cloning https://github.com/taoning/pyenergyplus_wheels to /private/var/folders/c2/tthc2_6j741c3rvx9vpjppwh0000gn/T/pip-req-build-ihxnqfnq
Running command git clone --filter=blob:none --quiet https://github.com/taoning/pyenergyplus_wheels /private/var/folders/c2/tthc2_6j741c3rvx9vpjppwh0000gn/T/pip-req-build-ihxnqfnq
Resolved https://github.com/taoning/pyenergyplus_wheels to commit 664456bc5428ad50ace2c2bc729bbc486afa0435
Preparing metadata (setup.py) ... done
Collecting pyenergyplus@ https://github.com/taoning/pyenergyplus/raw/main/wheels/darwin/pyenergyplus-23.1.0-py3-none-macosx_10_13_x86_64.whl
ERROR: HTTP error 404 while getting https://github.com/taoning/pyenergyplus/raw/main/wheels/darwin/pyenergyplus-23.1.0-py3-none-macosx_10_13_x86_64.whl
ERROR: Could not install requirement pyenergyplus@ https://github.com/taoning/pyenergyplus/raw/main/wheels/darwin/pyenergyplus-23.1.0-py3-none-macosx_10_13_x86_64.whl from https://github.com/taoning/pyenergyplus/raw/main/wheels/darwin/pyenergyplus-23.1.0-py3-none-macosx_10_13_x86_64.whl (from pyenergyplus-wheels==0.1.0) because of HTTP error 404 Client Error: Not Found for url: https://github.com/taoning/pyenergyplus/raw/main/wheels/darwin/pyenergyplus-23.1.0-py3-none-macosx_10_13_x86_64.whl for URL https://github.com/taoning/pyenergyplus/raw/main/wheels/darwin/pyenergyplus-23.1.0-py3-none-macosx_10_13_x86_64.whl

**Comment by rfritz** [comment]
To judge from the error message the example is out of date; there are two floor geometry parameters rather than one. Unfortunately, I not a frads expert, but maybe the initial line of the command should be something like:
```
    gen room 12 14 0 3 \
```
For more help ask over on the [frads discussion page](https://github.com/LBNL-ETA/frads/discussions) or maybe over on the [Radiance Discourse site](https://discourse.radiance-online.org/).

**Comment by koepferl** [comment]
oh yes, the \ disappeared on GitHub, but they are there in the terminal. So unfortunately this is not the case.

**Comment by rfritz** [comment]
But, four numbers instead of three. The error message is clear on that, though I'm only guessing that `flrflr` is a height.

**Comment by koepferl** [comment]
Thanks changing it to gen room 12 14 3 0 \ did work. I just copied this from the tutorial, I guess there was a typo there.

**Comment by taoning** [comment]
Resume frads issue discussion in frads
