### ISSUE TITLE
Question Regarding the next Release

### ISSUE THREAD

**Issue by JasmineLowen** [LBNL-ETA/Radiance#31]
I'm currently trying to [package the repo for nixpkgs](https://github.com/NixOS/nixpkgs/pull/307683). I wanted to go with the latest stable release 5.4. but [I ran into the following compile errors](https://github.com/NixOS/nixpkgs/pull/307683#discussion_r1588767967). Since there are already a few 6.0a pre-releases out there I kindly wanted to ask if and when you're planning to do the next major release. Packaging the pre-releases was rather easy and so that would help us a lot.

**Comment by Gregungory** [comment]
Hi Robert,

So great to have you working on this.  Unfortunately, it's not good timing for an official release, as 6.0a is really alpha at this stage, since few people have had a chance to take the new features out for a test ride.  You are of course welcome to put a package together in any case, but it may not be as stable/reliable as you like, at least as far as the new capabilities are concerned.

Cheers,
-Greg

> From: Robert Walter ***@***.***>
> Date: May 2, 2024 at 10:57:31 PM PDT
> To: LBNL-ETA/Radiance ***@***.***>
> Cc: Subscribed ***@***.***>
> 
> I'm currently trying to package the repo for nixpkgs <https://github.com/NixOS/nixpkgs/pull/307683>. I wanted to go with the latest stable release 5.4. but I ran into the following compile errors <https://github.com/NixOS/nixpkgs/pull/307683#discussion_r1588767967>. Since there are already a few 6.0a pre-releases out there I kindly wanted to ask if and when you're planning to do the next major release. Packaging the pre-releases was rather easy and so that would help us a lot.

**Comment by taoning** [comment]
Hi Robert,

I looked at your compile errors but couldn't figure out why (Other than a few missing libraries from cmake).  You mentioned 6.0a compiles so I am not sure what's the issue here.  I'd be happy to help you get 5.4 compiled if you can give me a few pointer on how to reproduce this.  I assume I need to get Nix setup?

**Comment by JasmineLowen** [comment]
> Hi Robert, So great to have you working on this. Unfortunately, it's not good timing for an official release, as 6.0a is really alpha at this stage, since few people have had a chance to take the new features out for a test ride. You are of course welcome to put a package together in any case, but it may not be as stable/reliable as you like, at least as far as the new capabilities are concerned. Cheers, -Greg
> […](#)
> From: Robert Walter ***@***.***> Date: May 2, 2024 at 10:57:31 PM PDT To: LBNL-ETA/Radiance ***@***.***> Cc: Subscribed ***@***.***> I'm currently trying to package the repo for nixpkgs <[NixOS/nixpkgs#307683](https://github.com/NixOS/nixpkgs/pull/307683)>. I wanted to go with the latest stable release 5.4. but I ran into the following compile errors <[NixOS/nixpkgs#307683 (comment)](https://github.com/NixOS/nixpkgs/pull/307683#discussion_r1588767967)>. Since there are already a few 6.0a pre-releases out there I kindly wanted to ask if and when you're planning to do the next major release. Packaging the pre-releases was rather easy and so that would help us a lot.

Hi Greg,

thanks for the fast reply and the information. I will try to stick to the 5.4. release for the package for the mean time then and maybe test out the alpha on my own.

All the best,
Robert

**Comment by JasmineLowen** [comment]
> Hi Robert,
> 
> I looked at your compile errors but couldn't figure out why (Other than a few missing libraries from cmake). You mentioned 6.0a compiles so I am not sure what's the issue here. I'd be happy to help you get 5.4 compiled if you can give me a few pointer on how to reproduce this.

I'm also still tapping in the dark and I'm afraid there is not really any additional info other than what I already posted. You can try to join me packaging though, but I guess this could be hard if you have no experiences with nix yet. Feel free to ask me anything if you want though!

> I assume I need to get Nix setup?

Yes, probably something along the lines here https://nixos.org/manual/nix/stable/installation/installing-binary#single-user-installation. Note that you can uninstall it simply by removing the `/nix` dir, so it shouldn't pollute your system https://nixos.org/manual/nix/stable/installation/uninstall#single-user 

After that you can checkout the PR in the nixpkgs repo and run `nix-build -A radiance` to build the package. All the relevant source code can be found here: https://github.com/NixOS/nixpkgs/blob/7f6552aba21c8dd0d2b74c3be9e4fd371fffee63/pkgs/by-name/ra/radiance/package.nix

**Comment by JasmineLowen** [comment]
I was just able to fix the error while packaging which means radiance should be available under nixpkgs soon. Thanks for the help and answers. I'm closing this issue here now!
