### ISSUE TITLE
Some wrong when use the software!!!

### ISSUE THREAD

**Issue by Dawe890311** [LBNL-ETA/Radiance#32]
when I install the software and run it ,the "message : rtrace: system - cannot find function file "rayinit.cal": No such file or directory" appear!

**Comment by Dawe890311** [comment]
![image](https://github.com/user-attachments/assets/4bccacf2-d353-471c-b274-f9fae849c098)

**Comment by Dawe890311** [comment]
![image](https://github.com/user-attachments/assets/26487000-30c4-4ba6-9af1-4a0b31613223)

**Comment by taoning** [comment]
If you installed using the `.pkg` installer, the installer should have set the `RAYPATH` for you.
If you just copy/paste the binaries, you might need to set `RAYPATH` manually.
You can set it using anyway by running `echo RAYPATH=.:/usr/local/radiance/lib >> ~/.zshrc`, assuming you are using zsh on mac.

**Comment by Dawe890311** [comment]
Thank you for your response. But I just installed using the .pkg installer and don't set the path.

**Comment by Dawe890311** [comment]
I use the `radiance` because install the `bifacial_radiance ` python package, you can see the install [link](https://bifacial-radiance.readthedocs.io/en/latest/user_guide/installation.html#step-0-prerequisites-step-0) .
I install the `bifacial_radiance` package and `radiance`, But when I use it, the error come ""message : rtrace: system - cannot find function file "rayinit.cal": No such file or directory""

**Comment by taoning** [comment]
you can check whether `RAYPATH` is set by `echo $RAYPATH`. If nothing returns, then you didn't set it.
Set it by `export RAYPATH=/usr/local/radiance/lib`, which will work for the session.
Or put this line in you `.zshrc` so that it works for every session.

**Comment by Dawe890311** [comment]
![image](https://github.com/user-attachments/assets/9189f906-65b8-4834-9ceb-7468561e4163)
![image](https://github.com/user-attachments/assets/75531f60-9ca9-4744-95e9-8e4450826617)
But It doesn't work again !!
![image](https://github.com/user-attachments/assets/69ee8c63-6c78-460c-8a65-748f117f2552)

**Comment by taoning** [comment]
I have no way of supporting the `bifacial_radiance` code you are showing. For that, you'd need to seek help from the library authors.

**Comment by Dawe890311** [comment]
Thank You anyway!!!
