### ISSUE TITLE
missing vchars.mta

### ISSUE THREAD

**Issue by zhangxiaojiawow** [LBNL-ETA/Radiance#33]
I have installed radiance from installers [Radiance 5.4 (2023-11-05)](https://github.com/LBNL-ETA/Radiance/releases/tag/rad5R4), when I run this command ` objline objects/chair.rad | x11meta`, the output is an error message: 
```
bash: /usr/local/radiance/bin/objline: /bin/csh: bad interpreter: No such file or directory
fatal - cannot open file "/usr/local/lib/meta/vchars.mta", mode "r" 
```

how can i get the missing file?

**Comment by taoning** [comment]
You can find it in the auxiliary package in the release.

**Comment by Gregungory** [comment]
You may also need to install the C-shell on your system, which does not come with Radiance.

Cheers,
-Greg
