### ISSUE TITLE
Looking for Pre-Compiled Installers

### ISSUE THREAD

**Issue by justine14-rgb** [LBNL-ETA/Radiance#34]
I cannot seem to exist the loop of downloads and installer .exe files to have a palpable app and user interface. Is there anywhere you can link me to a pre-compiled installer or concrete instructions as to how to download? Thanks.

**Comment by Gregungory** [comment]
There is no user interface in Radiance.  It is mostly command-line based tools.  You can check out the tutorials at:

	https://www.radiance-online.org/learning <https://www.radiance-online.org/learning>

Best,
-Greg
